### ISSUE TITLE
Add formspree for 'Send us an email' form action

### ISSUE THREAD

**Issue by jeffbrl** [onweru/ksrepo#10]
Email should be info@konekti.us. Please fix the "input" tags as needed.
```
<form action="https://formspree.io/your@email.com"
      method="POST">
    <input type="text" name="name">
    <input type="email" name="_replyto">
    <input type="submit" value="Send">
</form>
```

**Comment by onweru** [comment]
I'm familiar with formspree ... I will intergrate it

**Comment by jeffbrl** [comment]
After hitting submit, "Email sending..." displays indefinitely. No email is sent.

**Comment by jeffbrl** [comment]
Looks like the form action is calling an invalid URL rather than the formspree URL.

[2017-05-21 17:05:58] ERROR `/php/reachus.php' not found.

**Comment by onweru** [comment]
I will fix the bug

**Comment by onweru** [comment]
Kindly check the form

**Comment by jeffbrl** [comment]
Fix confirmed. Thank you.
