### ISSUE TITLE
Restore disqus integration

### ISSUE THREAD

**Issue by jeffbrl** [onweru/ksrepo#11]
The disquss integration from the prototype site is missing.

**Comment by onweru** [comment]
It actually there. The reason it's not syncing is because i don't know the exact disqus shortname for konekti systems. Once i have that, it will work

**Comment by jeffbrl** [comment]
I see the error about syncing on the site you are hosting but not with my jekyll deveopment server. I assumed I'd see the same as I do on the prototype site at https://s3.us-east-2.amazonaws.com/konekti.us/blog-detail.html.

Production site will be http://konekti.us.

```
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://konekti-us.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
```

**Comment by onweru** [comment]
This one won't sync with the githbu.io subdomain ... See the readme.md

**Comment by jeffbrl** [comment]
You have a typo for s.src. Please change to "s.src = 'https://konekti-us.disqus.com/embed.js';"

**Comment by onweru** [comment]
Unlikely, that template is as is like given by the disqus API. Are you sure your disqus shortname is *konektius*?? https://help.disqus.com/customer/portal/articles/466208

**Comment by jeffbrl** [comment]
It's konekti-us.

**Comment by onweru** [comment]
I edited the disqus shortname in _config.yml file. Let me know if it syncs.

**Comment by jeffbrl** [comment]
Not syncing on http://konekti.us Let me do some troubleshooting.

**Comment by jeffbrl** [comment]
I opened a ticket with Disqus support. Everything looks right to me.

**Comment by jeffbrl** [comment]
Here is Disqus's reply.

We looked into it and found that the problem is likely being caused by how the ‘this.page.url’ variable is being assigned. Currently, you have it set as only a part of the path of the page. For it to work, you’ll need the full, canonical url of the page.

For ex:
Current: this.page.url = ‘/blog/2017/03/28/your-next-step.html’;

Recommened: this.page.url = ‘http://konekti.us/blog/2017/03/28/your-next-step.html’;

Let me know if you have further questions.

**Comment by onweru** [comment]
That will be useful.

**Comment by jeffbrl** [comment]
Working. Thank you.
