### ISSUE TITLE
Modify Blog Post Header

### ISSUE THREAD

**Issue by jeffbrl** [onweru/ksrepo#16]
Header Should include-

Blog Title
Author
Date

Remove-

Head Shot
Author Slogan
Twitter Follow button

![blog_detail](https://cloud.githubusercontent.com/assets/1028225/26280107/c2cb1f5a-3d95-11e7-92df-fc092b7d7fe7.png)

**Comment by onweru** [comment]
Head shot is the author's avatar, right?

**Comment by jeffbrl** [comment]
Yes. No avatar please.

**Comment by jeffbrl** [comment]
Completed. Thank you.
