### ISSUE TITLE
Home page not displaying properly

### ISSUE THREAD

**Issue by jeffbrl** [onweru/ksrepo#23]
![capture](https://cloud.githubusercontent.com/assets/1028225/26321067/5d5bca52-3ef3-11e7-8c0c-6dbcd328e678.PNG)

**Comment by onweru** [comment]
Looks like you're trying to set up the site at AWS ... kindly share the link.

**Comment by jeffbrl** [comment]
http://konekti.us/ is now live using GH pages. Home page displays correctly. Thank you.
