### ISSUE TITLE
Moving to AWS S3

### ISSUE THREAD

**Issue by onweru** [onweru/ksrepo#24]
If you're trying to host the site on S3, kindly check this resources
https://jekyllrb.com/docs/deployment-methods/
https://github.com/laurilehmijoki/s3_website
https://m.youtube.com/watch?feature=youtu.be&v=SOMonG8Iqak
Jekyll will need to build the site first so that everything can render correctly.

![img_4029](https://cloud.githubusercontent.com/assets/16350351/26323470/9f31fc5a-3f37-11e7-8493-6fafa70255d6.PNG)

**Comment by jeffbrl** [comment]
ICANN policy prevents me from transfering the domain to AWS for sixty days. Let's get this site working with github pages. I am working on this now.

**Comment by jeffbrl** [comment]
Page is live at http://konekti.us using GH pages.
