### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by jeffbrl** [onweru/ksrepo#27]
Please add brief, plain-text document. I don't need anything extensive. Just a few paragraphs. You can include links to other sites as needed.

Here are some things on my mind.

1. Version dependencies - Ruby, Jekyll, etc.
2. Regarding GH pages, what is the difference between master and gh-pages branches?
3. Is it possible to preview changes on GH pages? I know that I can use the jekyll dev server prior to committing the code. I am curious if I can do this without using the dev server.

**Comment by onweru** [comment]
I created a **documentation.md** file ... It's somewhat thorough. The idea is not that you will exhaust it at once, but rather you will find it helpful when you hit a dead end or things go sideways. 

I was unable to attach an image related to the * 'gh-pages and master branches'* question. So I will attach it in this thread. Basically you can switch the branch you're serving your site from. See the image below
![img_4044](https://cloud.githubusercontent.com/assets/16350351/26357109/ee08f9f6-3fd6-11e7-8684-0b990f7b4540.PNG)

**Comment by jeffbrl** [comment]
Documentation is very good. The only thing I am not sure about adding new main navigation links or modifying the existing  main navigation sections: Home, When to Engage Us, Testimonials, About Us. I see that part of this involves modifying _data/sections.yml. Would the next step be editing the HTML at https://raw.githubusercontent.com/onweru/ksrepo/master/index.md? If you can elaborate on what's involved here, I'd appreciate it.

We are very close to finishing.

**Comment by onweru** [comment]
Great question. If you want to add an item to the navigation, you will edit the _data/sections.yml file. The **id** value must mirror the id on the  index.md template (the one your referred to above).

In the screenshots below, I have highlighted the pattern. As for the content in the sections, it you will edit it directly. I would recommend pulling the repo to your local machine and experimenting with it. The documentation I provided will help you to progressively master the site in a way you can gain control over almost every aspect.
![img_4050](https://cloud.githubusercontent.com/assets/16350351/26366595/519d9b8a-3ff4-11e7-8c2c-37c64370a13d.PNG)
![img_4051](https://cloud.githubusercontent.com/assets/16350351/26366597/522d3204-3ff4-11e7-83b3-f2037f626fc7.PNG)
![img_4052](https://cloud.githubusercontent.com/assets/16350351/26366599/52b1ee4a-3ff4-11e7-9d2d-5ddd035ce816.PNG)
![img_4053](https://cloud.githubusercontent.com/assets/16350351/26366598/52af6f94-3ff4-11e7-84be-fc2ce288c6c6.PNG)

**Comment by jeffbrl** [comment]
Thank you.
