### ISSUE TITLE
Add Archives navigation to main blog page and blog detail page

### ISSUE THREAD

**Issue by jeffbrl** [onweru/ksrepo#9]
Achives should be by year, month with clickable expansion. See attached image.

![achives](https://cloud.githubusercontent.com/assets/1028225/26278646/c40facfa-3d6d-11e7-8b1f-02820ae8e246.PNG)

**Comment by onweru** [comment]
This one is a tiny bit completed. I will get it right asap though

**Comment by onweru** [comment]
Check if it is okay.

**Comment by jeffbrl** [comment]
Not rendering properly. Shouldn't it include the dummy blog posts?

![archives](https://cloud.githubusercontent.com/assets/1028225/26320885/9dacd232-3ef2-11e7-863a-f2bcc8a48d49.PNG)

**Comment by onweru** [comment]
You moved the site to aws? Because https://onweru.github.io/ksrepo/ renders everything

**Comment by jeffbrl** [comment]
No. I'm using the jekyll dev server at http://104.236.86.186:4000/.

**Comment by onweru** [comment]
Hmm, I'm at a loss here ... because it appears that is looping through all the dummy posts but failing to do two things
* categorize them
* output the data itself 
I would like to see the docs for the jekyll dev server you're using. I haven't used it before personally

**Comment by jeffbrl** [comment]
```
jeffl@ubuntu-512mb-nyc3-01:~/ksrepo$ bundle exec jekyll -v
jekyll 3.3.1
jeffl@ubuntu-512mb-nyc3-01:~/ksrepo$ bundle exec jekyll serve --host=104.236.86.186
Configuration file: /home/jeffl/ksrepo/_config.yml
Configuration file: /home/jeffl/ksrepo/_config.yml
            Source: /home/jeffl/ksrepo
       Destination: /home/jeffl/ksrepo/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.461 seconds.
 Auto-regeneration: enabled for '/home/jeffl/ksrepo'
Configuration file: /home/jeffl/ksrepo/_config.yml
    Server address: http://104.236.86.186:4000/
  Server running... press ctrl-c to stop.
```

**Comment by jeffbrl** [comment]
Now that I migrated to GH pages, it looks better. Can you include summarization by year as depicted in the picture from the first comment above?

**Comment by onweru** [comment]
Absolutely.

**Comment by jeffbrl** [comment]
Looks great. Thank you.
